name: Deploy Site to S3

permissions:
  id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
  contents: read  # Permits your action to read this repo.

on:
  push:
    branches:
      - main

jobs:
  deploy_to_s3:
    runs-on: ubuntu-latest
    steps:
      # - name: Show region
      #   run: echo "Region is ${{ vars.AWS_TARGET_REGION }}"
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          role-session-name: "GitHubActions-DeployLayerStack"
          aws-region: ${{ vars.AWS_TARGET_REGION }}

      - name: Read node the version from package.json
        uses: skjnldsv/read-package-engines-version-actions@v2
        id: package-engines-versions
      # - name: Show node version number
      #   run: echo "Node version is ${{ steps.package-engines-versions.outputs.nodeVersion }}"
      - name: Use Node.js ${{ steps.package-engines-versions.outputs.nodeVersion }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.package-engines-versions.outputs.nodeVersion }}
          cache: 'npm'

      ## Deploying the Vite Application to S3
      - name: Install Node modules
        run: npm ci
      - name: Build React Vite Application
        run: npm run build
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
        # run: aws s3 sync . s3://${{ secrets.BUCKET_ID }} --delete
      # - name: Create CloudFront invalidation
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"