name: Deploy LambdaStack

permissions:
  id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
  contents: read  # Permits your action to read this repo.

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda_stack_or_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_TARGET_REGION }}
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          role-session-name: "GitHubActions-DeployLayerStack"

      - name: Read node the version from package.json
        uses: skjnldsv/read-package-engines-version-actions@v2
        id: package-engines-versions
      - name: Show node version number
        run: echo "Node version is ${{ steps.package-engines-versions.outputs.nodeVersion }}"
      - name: Use Node.js ${{ steps.package-engines-versions.outputs.nodeVersion }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.package-engines-versions.outputs.nodeVersion }}
          cache: 'npm'

      ## Deploying the LambdaStack via CDK is a toy example, so we don't need to do it here
      # - name: Deploy LambdaStack (via CDK)
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'deploy'
      #     cdk_stack: 'LambdaStack'
      #     cdk_args: '--require-approval never' # This is a toy example, so we don't need to approve changes
      #     actions_comment: false

      ## Deploying the Astro application to S3 and CloudFront
      # - name: Install Node modules
      #   run: npm ci
      # - name: Build Astro application
      #   run: npm run build
      # - name: Deploy to S3
      #   run: aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
      # - name: Create CloudFront invalidation
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"